#!/usr/bin/python2

import os
import getpass

if __name__ == '__main__':

    os.chdir("dist")
    for f in os.listdir('.'):
        if f.endswith('asc'):
            continue
        os.system("keybase sign -i "+str(f)+" -b -o "+str(f))
    os.chdir("..")



